name: test
on:
  push:
    branches:
      - main
      - master
  pull_request:

permissions:
  contents: read

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    env:
      CONFIG_PATH: ./config/config.yaml
      CONFIG_PATH_TEST: ../config/config.yaml
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.22'
      - name: Install Dependencies
        run: go mod download
      - name: Start Application
        run: go run cmd/grpc-nmap/main.go & 
          sleep 5  
      - name: Run Tests
        run: make test
      - name: Stop Application
        run: killall main || true
